# -- coding: utf-8 --

import curses

def set_theme_colors(theme):
    """Initialise les paires de couleurs Curses en fonction du thème choisi."""
    curses.use_default_colors()
    # PAIRES: 0-8:Base, 9-12:Fichiers, 13-16:Syntaxe, 17:Aperçu Couleur

    if theme == "light":
        curses.init_pair(0, curses.COLOR_BLACK, curses.COLOR_WHITE)
        curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)
        curses.init_pair(2, curses.COLOR_WHITE, curses.COLOR_BLACK)
        curses.init_pair(3, curses.COLOR_BLUE, curses.COLOR_WHITE)
        curses.init_pair(4, curses.COLOR_GREEN, curses.COLOR_WHITE)
        curses.init_pair(5, curses.COLOR_MAGENTA, curses.COLOR_WHITE)
        curses.init_pair(6, curses.COLOR_RED, curses.COLOR_WHITE)
        curses.init_pair(7, curses.COLOR_CYAN, curses.COLOR_WHITE)
        curses.init_pair(8, curses.COLOR_BLUE, curses.COLOR_WHITE)
        curses.init_pair(9, curses.COLOR_BLUE, curses.COLOR_WHITE)
        curses.init_pair(10, curses.COLOR_GREEN, curses.COLOR_WHITE)
        curses.init_pair(11, curses.COLOR_BLACK, curses.COLOR_WHITE)
        curses.init_pair(12, curses.COLOR_RED, curses.COLOR_WHITE)
        curses.init_pair(13, curses.COLOR_RED, curses.COLOR_WHITE)
        curses.init_pair(14, curses.COLOR_CYAN, curses.COLOR_WHITE)
        curses.init_pair(15, curses.COLOR_BLUE, curses.COLOR_WHITE)
        curses.init_pair(16, curses.COLOR_MAGENTA, curses.COLOR_WHITE)
    elif theme == "ocean":
        curses.init_pair(0, curses.COLOR_WHITE, 23)
        curses.init_pair(1, curses.COLOR_BLACK, curses.COLOR_CYAN)
        curses.init_pair(2, curses.COLOR_BLACK, curses.COLOR_CYAN)
        curses.init_pair(3, curses.COLOR_CYAN, 23)
        curses.init_pair(4, 114, 23)
        curses.init_pair(5, 244, 23)
        curses.init_pair(6, 185, 23)
        curses.init_pair(7, curses.COLOR_CYAN, 23)
        curses.init_pair(8, 211, 23)
        curses.init_pair(9, curses.COLOR_YELLOW, 23)
        curses.init_pair(10, curses.COLOR_GREEN, 23)
        curses.init_pair(11, curses.COLOR_WHITE, 23)
        curses.init_pair(12, curses.COLOR_RED, 23)
        curses.init_pair(13, 185, 23)
        curses.init_pair(14, curses.COLOR_CYAN, 23)
        curses.init_pair(15, 211, 23)
        curses.init_pair(16, 153, 23)
    elif theme == "synthwave":
        curses.init_pair(0, 225, 54)
        curses.init_pair(1, curses.COLOR_BLACK, curses.COLOR_MAGENTA)
        curses.init_pair(2, curses.COLOR_BLACK, curses.COLOR_MAGENTA)
        curses.init_pair(3, curses.COLOR_CYAN, 54)
        curses.init_pair(4, 114, 54)
        curses.init_pair(5, 244, 54)
        curses.init_pair(6, 205, 54)
        curses.init_pair(7, curses.COLOR_CYAN, 54)
        curses.init_pair(8, curses.COLOR_YELLOW, 54)
        curses.init_pair(9, curses.COLOR_CYAN, 54)
        curses.init_pair(10, curses.COLOR_GREEN, 54)
        curses.init_pair(11, 225, 54)
        curses.init_pair(12, curses.COLOR_MAGENTA, 54)
        curses.init_pair(13, 205, 54)
        curses.init_pair(14, curses.COLOR_CYAN, 54)
        curses.init_pair(15, curses.COLOR_YELLOW, 54)
        curses.init_pair(16, 135, 54)
    else:  # dark (default)
        curses.init_pair(0, curses.COLOR_WHITE, -1)
        curses.init_pair(1, curses.COLOR_WHITE, curses.COLOR_BLUE)
        curses.init_pair(2, curses.COLOR_BLACK, curses.COLOR_WHITE)
        curses.init_pair(3, curses.COLOR_BLUE, -1)
        curses.init_pair(4, curses.COLOR_YELLOW, -1)
        curses.init_pair(5, curses.COLOR_MAGENTA, -1)
        curses.init_pair(6, 68, -1)
        curses.init_pair(7, curses.COLOR_WHITE, -1)
        curses.init_pair(8, curses.COLOR_RED, -1)
        curses.init_pair(9, curses.COLOR_YELLOW, -1)
        curses.init_pair(10, curses.COLOR_GREEN, -1)
        curses.init_pair(11, curses.COLOR_WHITE, -1)
        curses.init_pair(12, curses.COLOR_RED, -1)
        curses.init_pair(13, 68, -1)
        curses.init_pair(14, curses.COLOR_CYAN, -1)
        curses.init_pair(15, curses.COLOR_RED, -1)
        curses.init_pair(16, 45, -1)
    # La paire 17 est initialisée dynamiquement par la fonction d'aperçu de couleur